; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.4.0 on Sat Jan 27 2024 18:01:05 GMT+0100 (Mitteleuropäische Normalzeit)
M280 P0 S90 ; retract BLTouch

